### PR TITLE
RconTroll 0.1.9004 aggregate & plot methods for sim(stack)

### PR DESCRIPTION
**Pull request by sylvainschmitt**
# RconTroll 0.1.9004

* `TROLLsimstack`: rename compressed in aggregated and document all slot
* `aggregate.TROLLsimstack` method
* `stack.TROLLsim` in its own file with doc
* `plot.TROLLsimstack` for (stack,any) with base, ggplot2 and plotly
* `plot.TROLLsimstack` for (stack,stack) to compare with a control
* `plot.TROLLsim` using `plot.TROLLsimstack`

### CODE REVIEW

**Comment by sylvainschmitt** [comment]
# RconTroll 0.1.9005

* New possibilities in plotting `what` argument (agb, gpp, litterfall, all abund, all ba, all R, all final_pattern, all disturbance)
* `inventoryFromOutput` fixed
* Joining `plot` methods in one file with only one doc
* Joining `print` methods in one file with only one doc
* Joining `summary` methods in one file with only one doc
* Corrected all WARNINGs and NOTEs in R CMD check
* Corrected part of `goodpractice::gp()` recomendations
* Add `cran-comment.md` to justify R CMD check NOTEs

**Comment by sylvainschmitt** [comment]
And this time we passed the Travis-CI build check [Travis-CI Build Status](https://travis-ci.org/sylvainschmitt/RconTroll) !

*but still no coverage [Coverage Status](https://codecov.io/github/sylvainschmitt/RconTroll?branch=master) ...*

**Comment by sylvainschmitt** [comment]
Sorry already new push needed for loadStack function:

# RconTroll 0.1.9006

* `loadStack` function
* Correct `plotly` and `ggplot2` namespaces issues
* insert wip badge in `README` stability-wip

**Comment by sylvainschmitt** [comment]
New plot options needed for sensitivity analysis, see image at the end...

# RconTroll 0.1.9007

* New possibilities in plotting `what` argument : diversity and rank-abundance (disturbed and final)
* New possibilities in plotting `what` argument : functional traits density plots (disturbed and final)

diversity
rank-abundance
wsg

**Comment by fischer-fjd** [comment]
Request approved! Thanks

**Pull request merged**
